spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  bus:
    enabled: true
    trace:
      enabled: true
management:
  endpoints:
    web:
     exposure:
      include: bus-refresh
